---
language: python
services: docker

addons:
  apt:
    packages:
      - python3-pip

env:
  global:
    - GIT_BASE="https://github.com/respheal"
    - ROLE_DIR="/home/travis/.ansible/roles"
  matrix:
    - MOLECULE_DISTRO="centos-7"
    - MOLECULE_DISTRO="centos-8"
    - MOLECULE_DISTRO="debian-9"
    - MOLECULE_DISTRO="debian-10"
    - MOLECULE_DISTRO="ubuntu-16.04"
    - MOLECULE_DISTRO="ubuntu-18.04"
    - MOLECULE_DISTRO="ubuntu-20.04"

install:
  - pip install -r requirements.txt
  - git clone $GIT_BASE/monit $ROLE_DIR/ansible-role-monit

script:
  - molecule test
