# tasks/facts.yml

- name: Include os_family vars
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

# Check required variables for valid values
- name: Check monit_config_dir
  fail:
    msg: |
      Invalid value for 'monit_config_dir': {{ monit_config_dir }}

      Supported types  : String
      Supported values : Any non-null string
  when: >-
    monit_config_dir is not string
    or monit_config_dir == 0

- name: Check monitored_services
  fail:
    msg: |
      Invalid value for 'monitored_services': {{ monitored_services }}

      Supported types  : List, String
      Supported values : Any non-null list or string
  when: >-
    monitored_services is not iterable
    or monitored_services == 0

# Remove service from list of monitored_services if not part of playbook
- name: Check monitored services
  set_fact:
    monitored_services: "{{ monitored_services | difference([item.daemon_name]) }}"
  when: >-
    item.var_name not in vars
    or lookup('vars', item.var_name) is not string
    or lookup('vars', item.var_name) == 0
  loop:
    - { var_name: 'apache_daemon',  daemon_name: 'httpd'   }
    - { var_name: 'mysql_daemon',   daemon_name: 'mariadb' }
    - { var_name: 'nginx_daemon',   daemon_name: 'nginx'   }
    - { var_name: 'php_fpm_daemon', daemon_name: 'php-fpm' }
    - { var_name: 'redis_daemon',   daemon_name: 'redis'   }
