# tasks/facts.yml

- name: Include os_family vars
  include_vars: Debian.yml
  when: ansible_os_family == "Debian"

# Check Apache
- name: Check Apache as a monitored service
  set_fact:
    monitored_services: "{{ monitored_services | difference(['httpd']) }}"
  when: >-
    apache_daemon is not string
    or apache_daemon == 0

#Check MySQL
- name: Check MySQL as a monitored service
  set_fact:
    monitored_services: "{{ monitored_services | difference(['mariadb']) }}"
  when: >-
    mysql_daemon is not string
    or mysql_daemon == 0

# Check nginx
- name: Check Nginx as a monitored service
  set_fact:
    monitored_services: "{{ monitored_services | difference(['nginx']) }}"
  when: >-
    nginx_daemon is not string
    or nginx_daemon == 0

# Check PHP
- name: Check PHP as a monitored service
  set_fact:
    monitored_services: "{{ monitored_services | difference(['php-fpm']) }}"
  when: >-
    php_fpm_daemon is not string
    or php_fpm_daemon == 0

# Check Redis
- name: Check redis_daemon as a monitored service
  set_fact:
    monitored_services: "{{ monitored_services | difference(['redis']) }}"
  when: >-
    redis_daemon is not string
    or redis_daemon == 0
